# This is a basic workflow to help you get started with Actions

name: CI

on:
    push:
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    formatting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Preparing for CI
              run: npm ci

            - name: Checking format
              run: npx prettier -c .

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Preparing for CI
              run: npm ci
              
            - name: Running tests
              uses: paambaati/codeclimate-action@v2.7.2
              env:
                CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                coverageCommand: npx nyc mocha
              debug: true
